### ISSUE TITLE
/vanish -d

### ISSUE THREAD

**Issue by ArcosCraft** [FoxBukkit/foxbukkit-lua#3]
Something to serve as a believable disconnection message when an administrator vanishes with an included "-d" flag.

The message should look like the normal disconnect message, for example, a non-staff user would see "[-] [Marr's] Arcos disconnected!" while a staff member would see "[Marr's] Arcos has disconnect vanished! Poof!" or a similar echo.

**Comment by Doridian** [comment]
I deliberately removed that because in all honesty I think it's retarded. Admins are often otherwise occupied.
The next problem: I cannot hide players from the playerlist (vanilla bukkit does this always, mine does never. There is no way I could make it only do it sometimes or whatever)
