### ISSUE TITLE
Coordinate Teleportation for Superbuilders

### ISSUE THREAD

**Issue by Marluxia114** [FoxBukkit/foxbukkit-lua#7]
Before the foxbukkit rewrite, Superbuilders and Architects used to be able to teleport to coordinates by using the command:
/tp -c <x> <y> <z>  (The y coordinate being optional and defaulting to surface if not used)

With the old /tp command and permissions being moved to staff-only, I am suggesting there be a flag added to /tpa to allow users to go to coordinates since there is already a -f flag.

I was considering /tpa -c x y z

**Comment by Doridian** [comment]
New command: /tpc X (Y) Z
/tp -c has been removed
